robot:
  name: mybot
  gravity: [0, 0, -9.81]
links:
  - name: base
    size: [0.3, 0.2, 0.1]
    mass: 5.0
  - name: thigh
    size: [0.1, 0.05, 0.05]
    mass: 1.0
joints:
  - name: hip
    type: hinge
    parent: base
    child: thigh
    axis: [0, 1, 0]
    range: [-90, 90]
actuators:
  - name: hip_motor
    joint: hip
    gear: 150
    ctrllimited: true
    ctrlrange: [-1, 1]
sensors:
  - type: jointpos
    joint: hip
contacts:
  # add contact geom tags here
